/**
 * Task Domain Model
 * Practical Exam 1: Firestore tasks collection schema
 */

export type TaskStatus = 'TODO' | 'IN_PROGRESS' | 'DONE';
export type TaskPriority = 'LOW' | 'MEDIUM' | 'HIGH';

export interface Task {
  /** Document ID auto-generated by Firestore */
  id: string;
  /** Task title (required) */
  title: string;
  /** Detailed task description (optional) */
  description?: string;
  /** Current lifecycle status */
  status: TaskStatus;
  /** Priority level */
  priority: TaskPriority;
  /** ISO Date string (YYYY-MM-DD) or null */
  dueDate?: string | null;
  /** Timestamp when task was created (ISO string or epoch milliseconds) */
  createdAt: string | number;
  /** Team identifier (reserved for Exam 2, null for now) */
  teamId?: string | null;
  /** Assignee user ID (reserved for Exam 2, null for now) */
  assigneeId?: string | null;
}

export interface CreateTaskDTO {
  title: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  dueDate?: string | null;
  teamId?: string | null;
  assigneeId?: string | null;
}

export interface UpdateTaskDTO {
  title?: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  dueDate?: string | null;
  teamId?: string | null;
  assigneeId?: string | null;
}

export type TaskFilterType = 'ALL' | TaskStatus;
export type TaskSortType = 'NEWEST' | 'OLDEST' | 'DUE_DATE' | 'PRIORITY';
